# Generated by Django 5.0.4 on 2024-04-25 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('qty', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('add_date', models.DateField(auto_now_add=True)),
                ('stock_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1)),
                ('material', models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Leather', 'Leather'), ('Silk', 'Silk'), ('Wool', 'Wool'), ('Linen', 'Linen'), ('Nylon', 'Nylon'), ('Rayon', 'Rayon'), ('Other', 'Other')], max_length=20)),
                ('pattern', models.CharField(choices=[('Solid', 'Solid'), ('Striped', 'Striped'), ('Floral', 'Floral'), ('Checkered', 'Checkered'), ('Abstract', 'Abstract'), ('Other', 'Other')], max_length=20)),
                ('colour', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Other', 'Other')], max_length=20)),
                ('texture', models.CharField(choices=[('Knit', 'Knit'), ('Woven', 'Woven'), ('Denim', 'Denim'), ('Velvet', 'Velvet'), ('Silky', 'Silky'), ('Other', 'Other')], max_length=20)),
                ('usages', models.ManyToManyField(to='main.usage')),
            ],
        ),
    ]
