# Generated by Django 5.0.4 on 2024-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categorychoice_image_alter_usage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorychoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category_choices'),
        ),
    ]
