# Generated by Django 5.0.4 on 2024-05-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_categorychoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_choices',
            field=models.ManyToManyField(to='main.categorychoice'),
        ),
    ]
