# Generated by Django 5.0.4 on 2024-05-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_choices_categorychoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='measurements',
            field=models.CharField(default=('Measurement be added',), max_length=255),
        ),
    ]
