# Generated by Django 5.0.4 on 2024-05-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_usage_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='measurements',
        ),
    ]
