# Generated by Django 5.0.4 on 2024-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='usages',
        ),
        migrations.AddField(
            model_name='usage',
            name='measurements',
            field=models.ManyToManyField(to='main.measurement'),
        ),
    ]
