# Generated by Django 5.0.4 on 2024-05-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_measurement_usages_usage_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.BooleanField(default=False),
        ),
    ]
