# Generated by Django 5.0.4 on 2024-05-09 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
