# Generated by Django 5.0.4 on 2024-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_product_stock_status_alter_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banner')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banner')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
