# Generated by Django 5.0.4 on 2024-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_bannermen_bannerwomen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermen',
            name='caption_colour',
            field=models.CharField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='bannerwomen',
            name='caption_colour',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
