# Generated by Django 5.0.4 on 2024-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_bannermen_caption_colour_bannerwomen_caption_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermen',
            name='caption_colour',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='bannerwomen',
            name='caption_colour',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
