# Generated by Django 5.0.4 on 2024-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart_cart_measurements_stitchingmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_measurements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipping'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=10),
        ),
        migrations.DeleteModel(
            name='StitchingMeasurement',
        ),
    ]
