# Generated by Django 5.0.4 on 2024-05-13 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_is_active'),
        ('orders', '0007_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address'),
        ),
    ]
