# Generated by Django 5.0.4 on 2024-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_measurements',
            field=models.TextField(default=None, null=True),
        ),
    ]
