# Generated by Django 5.0.4 on 2024-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_measurements',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
