# Generated by Django 5.0.4 on 2024-05-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_cart_cart_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
