# Generated by Django 5.0.4 on 2024-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
