# Generated by Django 5.0.4 on 2024-05-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_return'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='ReturnOrder',
        ),
    ]
