# Generated by Django 5.0.4 on 2024-05-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_return_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied'), ('S', 'Shipping'), ('R', 'Received')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipping'), ('D', 'Delivered'), ('C', 'Cancelled'), ('R', 'Returned')], default='P', max_length=10),
        ),
    ]
