# Generated by Django 5.0.4 on 2024-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_paymentorder_paymentcod_paymentprepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprepaid',
            name='orders',
            field=models.ManyToManyField(blank=True, to='orders.order'),
        ),
    ]
